### ISSUE TITLE
Tests on Windows fail

### ISSUE THREAD

**Issue by bbankowski** [letsdrink/ouzo#126]
Because of usage of /tmp in tests:
file_put_contents(/tmp/SampleConfigFile.php): failed to open stream: No such file or directory

We should be using Path::joinWithTemp() to fix it.

**Comment by piotrooo** [comment]
@bbankowski now is ok?

**Comment by bbankowski** [comment]
@piotrooo UriHelperGeneratorTest still fails, because of line breaks in string comparision.

**Comment by Danon** [comment]
both `UriHelperGenerator` and `UriHelperGeneratorTest` have hardcoded `\n`, instead of `PHP_EOL`, so all tests pass.

**Comment by Danon** [comment]
@bbankowski I fixed the one failing test on Windows, so this issue seems resolved now.
