### ISSUE TITLE
Add function to convert array to object

### ISSUE THREAD

**Issue by bbankowski** [letsdrink/ouzo#166]
Functions::toObject(array) -> so that I can use all Arrays functions that operates on objects (e.g. groupBy, orderBy).

**Comment by bbankowski** [comment]
And Arrays::toObject, which will return array of stdObjects.

**Comment by bbankowski** [comment]
Or another idea - maybe it is enough for Objects::getValue to support array.

**Comment by piotrooo** [comment]
I think this:

```php
if (is_array($object)) {
    return Arrays::getValue($object, $field, $default);
}
```

in `Objects::getValue` will be enough.
