### ISSUE TITLE
[ORM] use quotation for column names

### ISSUE THREAD

**Issue by christopherch** [letsdrink/ouzo#177]
Because there's a problem with columns which have reserved names (e.g. "from"). INSERT/SELECT/UPDATE/DELETE fail.

**Comment by piotrooo** [comment]
Quote depends of which driver is curently using:

Quotation:

MySQL `` ` ``
PostgreSQL `"`
Sqlite `"`

But it's possible to set MySQL quotation to `"` http://dev.mysql.com/doc/refman/5.0/en/ansi-mode.html, maybe this is good idea.

**Comment by PleaseDontKillMe** [comment]
Can we implement this quotation?

**Comment by piotrooo** [comment]
ASAP.

However PRs are always welcome ;)

**Comment by PleaseDontKillMe** [comment]
Are you sure quote for Sqlite is `"`?

>
'keyword'		A keyword in single quotes is a string literal.
"keyword"		A keyword in double-quotes is an identifier.
[keyword]		A keyword enclosed in square brackets is an identifier.
\`keyword\` A keyword enclosed in grave accents (ASCII code 96) is an identifier. 

What if it's `[]` or `"`

From http://www.sqlite.org/lang_keywords.html

**Comment by PleaseDontKillMe** [comment]
There's a problem with Order and GroupBy, because of diversity of possible inputs like filed names, field names with associated tables and/or aliases, raw sql queries and functions' invokations, etc.

Possible solution would be to use Db::raw('Count(*)')

**Comment by bbankowski** [comment]
Double-quote is fine, closing.
