### ISSUE TITLE
Priority to match route

### ISSUE THREAD

**Issue by piotrooo** [letsdrink/ouzo#183]
Case:

Route definition:
```php
Route::get('/users/:id', 'users#show');
Route::get('/users/get_contacts', 'users#get_contacts');
```

Now I call request `/users/get_contacts`, it should match to second route, but now is matched to the first. Routes with parameters should have low priority than exactly route.

**Comment by woru** [comment]
If it works in this order:

```php
Route::get('/users/get_contacts', 'users#get_contacts');
Route::get('/users/:id', 'users#show');
```
I wouldn't change anything.

**Comment by bbankowski** [comment]
Agree.
24 cze 2015 09:22 "woru" <notifications@github.com> napisał(a):

**Comment by piotrooo** [comment]
So, we do something with this?

**Comment by woru** [comment]
No
![grumpy-cat-definitely-did-not-make-100-million](https://cloud.githubusercontent.com/assets/239006/8771953/746f42ac-2ec7-11e5-9cf1-9c240c379868.jpg)
