### ISSUE TITLE
letsdrink/ouzo 1.5.0 requires symfony/console 2.5.7

### ISSUE THREAD

**Issue by dbirchak** [letsdrink/ouzo#188]
Are there plans to update dependency support for the current symfony/console (v2.7.2)?

**Comment by piotrooo** [comment]
For me is ok to up to v2.7.2.
I try to up to this version tests passed.

@woru @bbankowski what you think?

**Comment by dbirchak** [comment]
I think we should drink on it!  

After working through ouzo MVC I realized it was the the goodies i was looking for :). However, I’m excited to load it in IntelliJ, map it out and really dig in your MVC ORM implementation.

**Comment by bbankowski** [comment]
@dbirchak definately :)

@piotrooo I'm fine with that. Let's bump the version up and together with couple of bug fixes we can release it as a part of 1.5.1.

**Comment by piotrooo** [comment]
@dbirchak now is bumped version in trunk, we try to release ASAP.

**Comment by bbankowski** [comment]
Ouzo 1.5.1 with dependency to 2.7.2 is ready.
