### ISSUE TITLE
Any::of can't handle multiple regexp queries.

### ISSUE THREAD

**Issue by PleaseDontKillMe** [letsdrink/ouzo#213]
$builder->where('column' => 'value');  // works
    $builder->where("column ~ 'regexp'");  // works

    $builder->where(Any:of([
      'field1' => 'value',
      'field2' => 'value'
    ]);                                    // works

    $builder->where(Any:of([
      "field1 ~ 'regexp'",
      "field2 ~ 'regexp'"
    ]);                                    // doesn't work

Error message:

    Ouzo\DbException : 
    Exception: query: SELECT table.* FROM table WHERE 0 = ? with params: ["field ~ 'regexp'"] failed: ERROR:  
    invalid input syntax for integer: "field ~ 'regexp'" (22P02 7)

It treats "field ~ 'regexp'" as a field value, but it shouldn't.

**Comment by bbankowski** [comment]
Looks like we could create a restriction for that e.g.

'field1' => Restrictions::regexp('.*')

Keep in mind we have to implement it for multiple databases under the hood
('~' is Postgres only).

So, if you need it quickly, just create your custom restriction for
postgres only in your codebase. Should be pretty simple.
