### ISSUE TITLE
Chainable ArrayAssert

### ISSUE THREAD

**Issue by PleaseDontKillMe** [letsdrink/ouzo#231]
We could achieve something like this

```php
/**
 * @test
 */
public function shouldFetchCompanies()
{
    // when
    $companies = $cache->getCompanies();

    // then
    Assert::thatArray($companies)
        ->onProperty('name')->containsExactly('Woru Inc. Sp. z o.o.')->hasSize(1)
        ->onProperty('id')->containsExactly('ajdi')->hasSize(1);
        ->onProperty('owner')->containsOnly('me');
}
```

+ (+) Multiple `onProperty` in one assert
+ (+) Still can chain conditions

- (-) You can not make recursive `onProperty` (While getting object of object,  you cannot get property of the second object again)
- (+) recursive `onProperty` is useless anyway, because we always want to check arrays, strings and integers (primitive values)

All we have to do is:
+ ArrayAssert must accept second optional field (lets call it `$originalData`). Constructor is private and access is via static factory, so this optional parameter is never revealed.
```php
private function __construct(array $actual, array $originalData = [])
{
    // ...
    $this->_originalData = $originalData ?: $actual;
}
```
+ `onProperty` must pass its `$originalData` param to the new instance it creates
```php

public function onMethod($method)
{
    return new ArrayAssert(// ..
    }), $this->_originalData);
}
```
+ Every method with a condition (so, `constains`, `containsSequence`, `isEqualTo`, `excludes`, etc.) 
must replace
``` 
return $this;
 ```
to
```
return $this->then();
```
and method `then()` is implemented like this 
```
return new ArrayAssert($this->originalData);
```

**Comment by woru** [comment]
I don't like this idea. It's counter intuitive and inconsistent with existing libraries (like fest etc).

However, we can do something like in assert4j:

```php
assertThat(fellowshipOfTheRingArray).extracting('name', 'getAge()')
                                    .contains(array("Boromir", 37),
                                                   array("Sam", 38),
                                                   array("Legolas", 1000));

```

**Comment by piotrooo** [comment]
@woru :+1:

**Comment by woru** [comment]
For one parameter, extracting should work just like onProperty or onMethod:

```php
assertThat(fellowshipOfTheRingArray).extracting('name')
                                    .contains("Boromir",
                                                   "Sam",,
                                                   "Legolas");

```
