### ISSUE TITLE
Why does ouzo allow for creating fields' names containing reserved keywords?

### ISSUE THREAD

**Issue by PleaseDontKillMe** [letsdrink/ouzo#235]
```php
class Role extends Model
{
    function __construct($attributes = [])
    {
        parent::__construct([
            'attributes' => $attributes,
            'fields' => ['name', 'create', 'read', 'update', 'delete']]);
    }
}
```
Shouldn't it throw an error?

Beacuse inserting such an object causes:
`Exception: query: INSERT INTO roles (name, create) VALUES (?, ?) with params: [1, 1] failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create) VALUES (1, 1)'`

And if it's desired behaviour, shouldn't ouzo escape those names so they can be peacefully inserted to the database?

**Comment by woru** [comment]
https://github.com/letsdrink/ouzo/issues/177
