### ISSUE TITLE
Cursor support in ORM

### ISSUE THREAD

**Issue by bbankowski** [letsdrink/ouzo#241]
E.g.
```
Model::where()->fetchIterator();
```

fetchIterator could return iterator (new IteratorIterator on PDOStatement) which is using cursor under the hood. It could be used together with BatchingIterator.

Maybe instead of fetchIterator we could make StatementExecutor iterable (but we should think when & how to log queries, which is how handled in fetch/fetchAll).

**Comment by woru** [comment]
Only
```php
Db::getInstance()->query(...)->fetchIterator();
```

ModelQueryBuilder::where()->with(...)->fetchIterator(); would be very hard to implement
