### ISSUE TITLE
Scaffolding for new routes

### ISSUE THREAD

**Issue by PleaseDontKillMe** [letsdrink/ouzo#249]
This:

``` ruby
console ouzo:routes --add users#assign
```

Could add method `assign` for `UsersController` and also add route 

``` php
Route::get('/users/assign', 'users#assign');
```

And also regenerate uri helper. For generating other methods (`post`, `resource` etc) a flag could be used.

**Comment by woru** [comment]
I don't know if 
```
console ouzo:routes
```
is a good name.

How is it called in RoR?

**Comment by PleaseDontKillMe** [comment]
Duplicate of #238

**Comment by Danon** [comment]
In RoR that is 
```sh
rails generate resource User
```

so maybe

```sh
console ouzo:resource users#assign
```
?
