### ISSUE TITLE
Add twig support

### ISSUE THREAD

**Issue by woru** [letsdrink/ouzo#37]
http://twig.sensiolabs.org/

Ouzo should be able to render .twig files.

There can be a config prop defining template engine.

**Comment by bbankowski** [comment]
I've started some refactorings. Right now it is possible to use custom renderer (that implements `ViewRenderer` interface). It can be set up in config:
```
$config['renderer']['default'] = '\MyCustom\Renderer';
$config['renderer']['my_view'] = '\MyCustom\Renderer';
```

The order is as follows:
* get renderer by view name
* if not specified - get default renderer
* if not specified - PhtmlRenderer wil be used

**Comment by bbankowski** [comment]
In order to get Twig up and running app composer has to be updated with:
```
  "require": {
      "twig/twig":"1.18.1"
  }
```

**Comment by bbankowski** [comment]
We should look at `ViewPathResolver` as well, it has some logic that should take other renderers into consideration.

**Comment by bbankowski** [comment]
Added configuration for TwigRenderer, so that options to Twig_Environment can be passed. E.g.
```php
$config['renderer']['twig'] = array('debug' => true);
```
