### ISSUE TITLE
add Optional

### ISSUE THREAD

**Issue by woru** [letsdrink/ouzo#72]
https://code.google.com/p/guava-libraries/wiki/UsingAndAvoidingNullExplained#Optional

Additionally, Optional can have **__call** that delegates call to the value and returns a new Optional for the result.

```php
Optional::fromNullable($user)->getDepartment()->getFullName()->get();

Optional::fromNullable($user)->getDepartment()->getFullName()->or('Unknown');

Optional::fromNullable($user)->level->or(1);
```

Alternative names:
```php
Optional::nullable($user)->level->get();
```

**Comment by bbankowski** [comment]
Implemented Optional based on Guava. No docs though.
