### ISSUE TITLE
ArrayAssert new method to test keys

### ISSUE THREAD

**Issue by piotrooo** [letsdrink/ouzo#8]
Maybe good idea will be add methods to testing array keys e.g.:
- `key`
- `keysOnly`
- `keysExactly`

**Comment by PleaseDontKillMe** [comment]
We could implement it, right?

**Comment by woru** [comment]
It would suffice to all a 'keys()' method returning array assert for array of keys.

**Comment by woru** [comment]
or extractingKeys?
```php
Assert::thatArray()->keys()->contains('one');
```
is not grammatically correct.

Does anyone have a better idea?

**Comment by bbankowski** [comment]
Assert::thatArray()->keysArray()...

W dniu środa, 9 listopada 2016 woru <notifications@github.com> napisał(a):

**Comment by PleaseDontKillMe** [comment]
```php
Assert::thatArray($array)->keyset()->contains('one');
```
